name: Deploy Dockerized Next.js to Cloud Server

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub (optional)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add this as a secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add this as a secret

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build --build-arg BACKEND_HOST=${{ secrets.BACKEND_HOST }} -t ibkr-fe:latest .

    # Step 4: Push Docker image to Docker Hub (optional)
    - name: Push Docker image to Docker Hub
      run: docker tag ibkr-fe:latest farha1/ibkr-fe:latest && docker push farha1/ibkr-fe:latest

    # Step 5: Deploy Docker image to server
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Pull the latest image (if using Docker Hub)
          docker pull farha1/ibkr-fe:latest

          # Stop and remove any existing container
          docker stop ibkr-fe || true
          docker rm ibkr-fe || true

          # Run the new container
          docker run -e BACKEND_HOST=${{ secrets.BACKEND_HOST }} -d \
            --name ibkr-fe \
            -p 3021:3021 \
            farha1/ibkr-fe:latest
